### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by garrettwilkin** [jonathanmelville/WebFeeds-Agent#1]
Hey Jonathan!

I'm on my next to last day at the Bangor Daily News and trying to implement a WebFeeds agent consumer on a short timeline for them. Your project looks like it would solve some of the main challenges for ingesting the feed. 

Is it still in use? Is it working well? Should we give it a shot?

**Comment by jonathanmelville** [comment]
Hi! So this definitely worked at the time that I checked it into Github. The paper that I wrote it for no longer has access to the AP entitlements that they did at the time so it's no longer in use. 

My guess is you might find some useful code in here for hacking together an app but I don't think you could drop this onto your server, fire it up and have it start ingesting without putting some work into it.

Sorry, I know that's not what you wanted to hear! I would say Node was a good fit for this if you decide to roll your own.
